### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by laaneoks** [lmbelo/MinIO4Delphi#1]
Is it possible to add sample uses to the project?

**Comment by lmbelo** [comment]
I have just updated the readme file with a brief instruction set. Let me know if that is enough.

**Comment by laaneoks** [comment]
Thanks for the example. Is it possible to add getting a file from a S3 server to the example?

**Comment by lmbelo** [comment]
You will find this info here: https://github.com/lmbelo/MinIO4Delphi/tree/main/samples/sample1
