### ISSUE TITLE
Envio multipart

### ISSUE THREAD

**Issue by rafaeldemedeiros** [lmbelo/MinIO4Delphi#2]
Bom dia Lucas. 
Fiz um teste com o seu código porém, obtive erro.
Eu montei um Minio local e tentei fazer o envio de um arquivo maior que 10MB (DEFAULT_DATA_CHUNK_SIZE). Neste caso, o envio seria feito usando o recurso de MultiParts dentro da função UploadLargeFile.
Você chegou a validar este código? Foi com a versão 12?

Abraços, 
Rafael

**Comment by lmbelo** [comment]
@rafaeldemedeiros,

o sistema apresenta alguma mensagem de erro? Por favor, poste aqui o seu erro com mais detalhes.

**Comment by lmbelo** [comment]
Percebi um problema, não sei se é o mesmo do seu... atualiza sua versão e faz um teste.

**Comment by rafaeldemedeiros** [comment]
Era este problema sim.
Funcionou. 
Muito obrigado.
