### ISSUE TITLE
OptionalParams na função GetBucket

### ISSUE THREAD

**Issue by rafaeldemedeiros** [lmbelo/MinIO4Delphi#4]
Olá Lucas.
Ao usar a função GetBucket (storageServer.GetBucket(strBucket,opcionais), os parâmetros opcionais estão sendo descartados.
É isso mesmo? Será que estou usando de forma errada?

Obrigado, 
Rafael

**Comment by lmbelo** [comment]
Rafael, preciso de um código de exemplo para investigar.

**Comment by rafaeldemedeiros** [comment]
Claro...
Adicionei o parâmetro "opcionais : TStringList" na função GetBucket

[Unit1.zip](https://github.com/user-attachments/files/16564549/Unit1.zip)


procedure TForm1.Button2Click(Sender: TObject);
var
  strBucket  : String;
  bucketInfo : TAmazonBucketResult;
  objectInfo : TAmazonObjectResult;
  **opcionais  : TStringList;**
  item       : TListItem;
  pastas     : string;
begin
  ListView1.Clear();
  opcionais := TStringList.Create();

  opcionais.Values['delimiter'] := '/';

  if (edPrefix.text <> '') then
  begin
    opcionais.Values['prefix'] := edPrefix.text;
  end;
  if (edMax.text <> '') then
  begin
    opcionais.Values['max-keys'] := edMax.text;
  end;

  if (ListBox1.ItemIndex >= 0) then
  begin
    strBucket := ListBox1.Items[ListBox1.ItemIndex];
    bucketInfo := storageServer.GetBucket(strBucket,**opcionais**);
    for objectInfo in bucketInfo.Objects do
    begin
      item := ListView1.Items.Add();
      item.Caption := objectInfo.Name;
      item.SubItems.Add(IntToStr(objectInfo.Size));
      item.SubItems.Add(objectInfo.LastModified);
    end;
    for pastas in bucketInfo.Prefixes do
    begin
      item := ListView1.Items.Add();
      item.Caption := pastas;
    end;
  end
  else
  begin
    ShowMessage('Selecione um bucket');
  end;
end;

**Comment by lmbelo** [comment]
Fiz o ajuste para o limite de registros. Aproveitei e adicionei seu exemplo aqui no repo.
